### ISSUE TITLE
Modal error since 1.8.2

### ISSUE THREAD

**Issue by gav-fyi** [themesberg/flowbite-svelte#1653]
### Describe the bug

Since upgrading to 1.8.2, I'm getting failed tests using a very simple modal example. These tests were passing in 1.8.1.

```
> zooscribe@1.0.0 test
> vitest run frontend/src/__tests__/components/AddEditTitleModal.svelte.test.js


 RUN  v3.2.4 /workspace

stderr | frontend/src/__tests__/components/AddEditTitleModal.svelte.test.js > AddEditTitleModal > renders modal with correct title
Error: Uncaught [TypeError: get(...)?.showModal is not a function]
    at reportException (/workspace/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at innerInvokeEventListeners (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
    at invokeEventListeners (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLDialogElementImpl._dispatch (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLDialogElementImpl.dispatchEvent (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLDialogElement.dispatchEvent (/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at /workspace/node_modules/svelte/src/internal/client/dom/elements/transitions.js:26:11
    at without_reactive_context (/workspace/node_modules/svelte/src/internal/client/dom/elements/bindings/shared.js:44:10)
    at dispatch_event (/workspace/node_modules/svelte/src/internal/client/dom/elements/transitions.js:25:26)
    at Object.in (/workspace/node_modules/svelte/src/internal/client/dom/elements/transitions.js:247:4) TypeError: __vite_ssr_import_1__.get(...)?.showModal is not a function
    at HTMLDialogElement.event_handler (/workspace/node_modules/flowbite-svelte/dist/modal/Modal.svelte:66:273)
    at HTMLDialogElement.handle (/workspace/node_modules/svelte/src/internal/client/dom/elements/attributes.js:389:20)
    at /workspace/node_modules/svelte/src/internal/client/dom/elements/events.js:61:21
    at without_reactive_context (/workspace/node_modules/svelte/src/internal/client/dom/elements/bindings/shared.js:44:10)
    at HTMLDialogElement.target_handler (/workspace/node_modules/svelte/src/internal/client/dom/elements/events.js:60:35)
    at HTMLDialogElement.callTheUserObjectsOperation (/workspace/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLDialogElementImpl._dispatch (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLDialogElementImpl.dispatchEvent (/workspace/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)

 ❯ frontend/src/__tests__/components/AddEditTitleModal.svelte.test.js (1 test | 1 failed) 127ms
   × AddEditTitleModal > renders modal with correct title 126ms
     → element.animate is not a function

        in <unknown>
        in Modal.svelte
        in AddEditTitleModal.svelte


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  frontend/src/__tests__/components/AddEditTitleModal.svelte.test.js > AddEditTitleModal > renders modal with correct title
TypeError: element.animate is not a function

        in <unknown>
        in Modal.svelte
        in AddEditTitleModal.svelte

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: get(...)?.showModal is not a function
 ❯ HTMLDialogElement.event_handler node_modules/flowbite-svelte/dist/modal/Modal.svelte:66:273

 ❯ HTMLDialogElement.handle node_modules/svelte/src/internal/client/dom/elements/attributes.js:389:20
 ❯ node_modules/svelte/src/internal/client/dom/elements/events.js:61:21
 ❯ without_reactive_context node_modules/svelte/src/internal/client/dom/elements/bindings/shared.js:44:10
 ❯ HTMLDialogElement.target_handler node_modules/svelte/src/internal/client/dom/elements/events.js:60:35
 ❯ HTMLDialogElement.callTheUserObjectsOperation node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30
 ❯ innerInvokeEventListeners node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25
 ❯ invokeEventListeners node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3
 ❯ HTMLDialogElementImpl._dispatch node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9
 ❯ HTMLDialogElementImpl.dispatchEvent node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17

This error originated in "frontend/src/__tests__/components/AddEditTitleModal.svelte.test.js" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "renders modal with correct title". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯


 Test Files  1 failed (1)
      Tests  1 failed (1)
     Errors  1 error
   Start at  07:15:32
   Duration  4.55s (transform 2.44s, setup 461ms, collect 3.08s, tests 127ms, environment 434ms, prepare 108ms)
```

### Component

```typescript
<script>
    import { Modal } from 'flowbite-svelte';

    let { isOpen = false } = $props();
</script>

<Modal
    title="Add Title"
    bind:open={isOpen}
>
    <div>Hello, World!</div>
</Modal>
```

### Test

```javascript
import { render } from '@testing-library/svelte';
import { describe, it, expect } from 'vitest';
import AddEditTitleModal from '../../components/AddEditTitleModal.svelte';

describe('AddEditTitleModal', () => {
    it('renders modal with correct title', () => {
        const { getByText } = render(AddEditTitleModal, { props: { isOpen: true } });
        expect(getByText('Add Title') != null).toBe(true);
    });
});
```

### Version and System Info

```shell
System:
    OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) arm64 unknown
    Memory: 2.35 GB / 7.75 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.17.0 - /usr/bin/node
    npm: 10.9.2 - /usr/bin/npm
  npmPackages:
    flowbite-svelte: ^1.8.1 => 1.8.1 
    svelte: ^5.34.8 => 5.34.8 
    vite: ^6.3.5 => 6.3.5
```

**Comment by jjagielka** [comment]
I can reproduce that. It's clearly connected with the addition of the `global` modifier to the transition:
```svelte
<dialog ... transition:transition|global={params} .../>
```
Let me dig into it.

**Comment by jjagielka** [comment]
This seems to be `svelte`/`@testing-library-svelte` issue and is connected with `mount` function that is used in the `render`.

```svelte
<script>
  import { fade } from "svelte/transition";
</script>

<div transition:fade|global>Add Title</div>
```
If you run the same test but replace the `Modal` by this simple component below you will experience the issue `TypeError: element.animate is not a function`. Seems like a component is created but not fully initialized (connected to DOM?).

By removing `global` the test passes smoothly.

**Comment by jjagielka** [comment]
Issued a ticket at `svelte`: https://github.com/sveltejs/svelte/issues/16258

**Comment by jjagielka** [comment]
We have an answer from https://github.com/sveltejs/svelte/issues/16258 
The issue seems to be in `jsdom` as some `Element` properties are not initialized correctly during the transition.

In Svelte `transition` is `local` by default, so the error was not initially visible, but would appear if you add `isOpen = true` later on like:
```js
        const { getByText } = render(AddEditTitleModal, { props: { isOpen: true } });
        flushSync();
        document.body.querySelector('button').click();  // <button onclick={() => (isOpen = !isOpen)}>Open</button>
        flushSync();
```
Recently added `global` modifier to `Dialog` makes the transition start immediately and therefore your test fails now. 

On top of the missing `animate` prop mentioned in the `jsdom` issue we can notice as well the lack of `showModal` on `HTMLDialogElement`.

The workaround is to mock those missing ones methods:

```js
import { render } from '@testing-library/svelte';
import { beforeAll, describe, expect, it, vi } from 'vitest';
import AddEditTitleModal from './AddEditTitleModal.svelte';

const mockMissingProps = () => {
    Element.prototype.animate = vi.fn().mockImplementation(() => ({ cancel: () => Promise.resolve() }));
    HTMLDialogElement.prototype.showModal = vi.fn().mockImplementation(() => Promise.resolve());
}

beforeAll(() => {
    mockMissingProps();
});

describe('AddEditTitleModal', () => {
    it('renders modal with correct title', () => {
        const { getByText } = render(AddEditTitleModal, { props: { isOpen: true } });
        expect(getByText('Add Title') != null).toBe(true);
    });
});
```
Hope that helps.

**Comment by gav-fyi** [comment]
Great. Thanks for the workaround. 👍🏻
